### ISSUE TITLE
getUser returns user is not connected to merchant only base on user.result

### ISSUE THREAD

**Issue by marjuszkiewicz** [schibsted/account-sdk-browser#111]
https://github.com/schibsted/account-sdk-browser/blob/master/src/identity.js#L544 
Probably it should be `user.userId && !user.result`

**Comment by olekenneth** [comment]
It should be `user.userId && user.clientAgreementAccepted && user.defaultAgreementAccepted`

**Comment by olekenneth** [comment]
And also this should be handled in the same when calling the `hasSession()` not just the `getUser()`

**Comment by marjuszkiewicz** [comment]
Thank you for your comment @olekenneth , `user.clientAgreementAccepted && user.defaultAgreementAccepted` are returned only for logged in and connected user. If result is `false`, as in this example https://github.com/schibsted/account-sdk-browser/blob/master/src/identity.js#L544 they are not present.

**Comment by marjuszkiewicz** [comment]
I did some investigation, backend returns `result: false` and LoginException if user haven't accept client agreement. So closing that issue
