### ISSUE TITLE
Performance impact/lock up in IE11

### ISSUE THREAD

**Issue by grzegorzkurtyka** [schibsted/account-sdk-browser#134]
There is an report of problems observed in IE11 triggered in `SDKError.js` possible infinite recursion on "toString" method.

**Comment by marjuszkiewicz** [comment]
In which version?
Isn't it fixed via https://github.com/schibsted/account-sdk-browser/pull/124 ?
Which was included in `v3.0.7`

**Comment by marjuszkiewicz** [comment]
As above, should be fixed from `v3.0.7`
