### ISSUE TITLE
Error caching on login

### ISSUE THREAD

**Issue by przbab** [schibsted/account-sdk-browser#62]
Hi,

I tested the SDK after recent rc.7 release and found behaviour that I believe is not correct. When I enter the page as not signed in user the 401 error response will be cached, then if I login and get redirected back to the page I still get the cached response and I'm not getting logged in. Clearing `hasSession-cache` key from local storage or waiting 5 minutes until it is invalidated before site refresh logs me in correctly.

I would suggest removing the cached response somewhere along the login procedure, similar to how logout function does it.

**Comment by torarvid** [comment]
Hi, and thanks for reporting an issue. I believe you are completely correct. The caching change was done in a bit of a hurry for rc.7 since our backend was being flooded by rc.6 and before.

**Comment by przbab** [comment]
Response is still cached incorrectly when using `loginUrl` instead of `login`.

**Comment by torarvid** [comment]
Right.. `loginUrl` just generates a URL and returns it, so it doesn’t have any “action” beyond that. Can I ask — out of curiosity — why you’re using that one instead of `login`?

**Comment by przbab** [comment]
I updated several projects from SPiD SDK to this one and all of them used method similar to `loginUrl`. The result of `loginUrl` is simply put in `href` of some `a` element without any event listener. I can also guarantee that more teams are doing it this way.

**Comment by torarvid** [comment]
I see. Thanks for the info. At least then it sounds like a workaround is “use `login` instead of `loginUrl`”
