### ISSUE TITLE
*Something* not working right with Identity.login on Chrome/iOS

### ISSUE THREAD

**Issue by torarvid** [schibsted/account-sdk-browser#76]
This issue was discovered by @vetleaa and at the time of this writing, if you use Chrome on iOS11, and go to pro.sdk-example.com and click Login, it works, but pre.sdk-example.com **doesn't** work.

The difference AFAICS, is that pre currently uses the itp modal logic, while pro doesn't (yet — this might have changed by the time you, dear reader, sees this).

What makes it more difficult, is that there's not really any good way to debug Chrome on iOS right now. Good luck!

**Comment by ksimons** [comment]
I'll give this thing a go 
https://stackoverflow.com/questions/11262236/ios-remote-debugging/22047495#22047495

**Comment by marjuszkiewicz** [comment]
I did http://jonsadka.com/blog/how-to-debug-a-chrome-specific-bug-on-ios-using-remote-debugging/ .  No issue with this debugger :( also I have noticed, if you click "use desktop version" in chrome login button works
