### ISSUE TITLE
Public api to bypass hasSession cache

### ISSUE THREAD

**Issue by erikfried** [schibsted/account-sdk-browser#87]
We have use cases where we want to bypass the hasSession cache.
We know the cache _is_ cleared when using the `Account.login()` method.

* We sometimes render login links from other origins than the destination where users end up after login. E g our sales poster pages have login and purchase links rendered in an iframe (this having a different origin) than the composing page. So even if we embed and use Account.login() from the iframe, the cache will be cleared on iframe.aftonbladet.se rather than www.aftonbladet.se. We could start posting messages from the iframe, but we´d prefer not to.
* We sometimes wish to use static <a href> links to login.

If we do one of the above and user returns to www.aftonbladet.se a stale state is still cached.
We can detect this, but are then forced to either do
`localStorage.removeItem('hasSession-cache')` or  temporarily set `identity. _enableSessionCaching = false`. 

None of those are good options, operating with SDK internals.

**Comment by torarvid** [comment]
Hi. I see your point. Now that all sites started using v3 of the sdk at the same time, and also iOS 12 (with ITP2) was released, we’re drowning in support at the moment, so I think I have to say “it’s gonna be a few days until I can get to this”.. Hope you understand and can work around it with internals in the mean time
